version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db_affiliate_market_connect
    restart: always
    environment:
      MYSQL_DATABASE: wp_db_affiliate_market_connect
      MYSQL_USER: wp_db_user
      MYSQL_PASSWORD: wp_db_password
      MYSQL_ROOT_PASSWORD: wp_db_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp_affiliate_market_connect
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_db_user
      WORDPRESS_DB_PASSWORD: wp_db_password
      WORDPRESS_DB_NAME: wp_db_affiliate_market_connect
    volumes:
      - ./:/var/www/html
    networks:
      - wordpress_network

volumes:
  db_data:
  wp_data:

networks:
  wordpress_network:
    driver: bridge
